"""WebSocket connection manager for /ws/inspections/{id}, plus a real
cross-process event relay: the `worker` container runs in a separate
process from the FastAPI `backend` container, so a narrative-ready event
generated by the worker can't call the backend's in-memory WebSocket
manager directly. Instead both sides publish onto a RabbitMQ fanout
exchange ("visireport.events.exchange"); the backend process runs a single
background consumer that relays incoming events to whichever browser
sockets are subscribed to that inspection_id. This is a real message-bus
hop, not a shared-memory shortcut.
"""
import asyncio
import json
import logging

import aio_pika
from fastapi import WebSocket

from app.config import get_settings

logger = logging.getLogger("visireport.ws")

EVENTS_EXCHANGE = "visireport.events.exchange"


class ConnectionManager:
    def __init__(self) -> None:
        self._connections: dict[int, set[WebSocket]] = {}

    async def connect(self, inspection_id: int, ws: WebSocket) -> None:
        await ws.accept()
        self._connections.setdefault(inspection_id, set()).add(ws)

    def disconnect(self, inspection_id: int, ws: WebSocket) -> None:
        conns = self._connections.get(inspection_id)
        if conns and ws in conns:
            conns.remove(ws)
            if not conns:
                self._connections.pop(inspection_id, None)

    async def send_local(self, inspection_id: int, event: dict) -> None:
        conns = list(self._connections.get(inspection_id, set()))
        for ws in conns:
            try:
                await ws.send_json(event)
            except Exception:
                self.disconnect(inspection_id, ws)


manager = ConnectionManager()


async def publish_external_event(inspection_id: int, event: dict) -> None:
    """Publish a progress/status event onto the shared fanout exchange.
    Used both by the in-process tiling loop (same container) and by the
    separate `worker` process, so all consumers see one consistent stream.
    """
    settings = get_settings()
    envelope = {"inspection_id": inspection_id, **event}
    try:
        connection = await aio_pika.connect_robust(settings.rabbitmq_url, timeout=5)
        async with connection:
            channel = await connection.channel()
            exchange = await channel.declare_exchange(EVENTS_EXCHANGE, aio_pika.ExchangeType.FANOUT, durable=True)
            await exchange.publish(
                aio_pika.Message(body=json.dumps(envelope).encode("utf-8"), content_type="application/json"),
                routing_key="",
            )
    except Exception:
        logger.exception("Failed to publish external WS event; falling back to local delivery only")
        await manager.send_local(inspection_id, event)


async def run_event_relay() -> None:
    """Background task started at FastAPI app startup: consumes the fanout
    exchange and relays each event to locally-connected WebSocket clients."""
    settings = get_settings()
    while True:
        try:
            connection = await aio_pika.connect_robust(settings.rabbitmq_url)
            async with connection:
                channel = await connection.channel()
                exchange = await channel.declare_exchange(
                    EVENTS_EXCHANGE, aio_pika.ExchangeType.FANOUT, durable=True
                )
                queue = await channel.declare_queue(exclusive=True, auto_delete=True)
                await queue.bind(exchange)
                logger.info("WS event relay connected to %s", EVENTS_EXCHANGE)
                async with queue.iterator() as it:
                    async for message in it:
                        async with message.process():
                            envelope = json.loads(message.body.decode("utf-8"))
                            inspection_id = envelope.pop("inspection_id")
                            await manager.send_local(inspection_id, envelope)
        except asyncio.CancelledError:
            raise
        except Exception:
            logger.exception("WS event relay lost connection; retrying in 3s")
            await asyncio.sleep(3)
